import type { Event, SportsClass, Category, UserSummary } from "./types"

export const mockUser: UserSummary = {
  name: "Matheus",
  avatarUrl: "",
  city: "Natal, RN",
}

export const mockEvents: Event[] = [
  {
    id: "1",
    title: "Corrida Noturna Ponta Negra",
    date: "2026-02-15T19:00:00",
    location: "Praia de Ponta Negra",
    gradient: "from-orange-500 to-rose-600",
    isFavorited: true,
    category: "Corrida",
  },
  {
    id: "2",
    title: "Campeonato de CrossFit",
    date: "2026-02-22T08:00:00",
    location: "Arena das Dunas",
    gradient: "from-blue-500 to-indigo-600",
    isFavorited: false,
    category: "CrossFit",
  },
  {
    id: "3",
    title: "Aulão de Yoga ao Ar Livre",
    date: "2026-03-01T06:30:00",
    location: "Parque da Cidade",
    gradient: "from-emerald-500 to-teal-600",
    isFavorited: false,
    category: "Yoga",
  },
  {
    id: "4",
    title: "Beach Tennis Open",
    date: "2026-03-08T07:00:00",
    location: "Praia do Meio",
    gradient: "from-amber-500 to-orange-600",
    isFavorited: false,
    category: "Beach Tennis",
  },
  {
    id: "5",
    title: "Maratona Fitness",
    date: "2026-03-15T05:00:00",
    location: "Via Costeira",
    gradient: "from-purple-500 to-pink-600",
    isFavorited: true,
    category: "Corrida",
  },
]

export const mockSportsClasses: SportsClass[] = [
  {
    id: "1",
    title: "CrossFit Matinal",
    instructor: "Prof. Ricardo",
    time: "06:00 - 07:00",
    daysOfWeek: ["Seg", "Qua", "Sex"],
    gradient: "from-red-500 to-orange-500",
    spotsLeft: 5,
    totalSpots: 20,
    level: "Intermediário",
  },
  {
    id: "2",
    title: "Yoga Flow",
    instructor: "Profa. Ana",
    time: "07:00 - 08:00",
    daysOfWeek: ["Ter", "Qui"],
    gradient: "from-green-500 to-emerald-500",
    spotsLeft: 8,
    totalSpots: 15,
    level: "Iniciante",
  },
  {
    id: "3",
    title: "Muay Thai",
    instructor: "Prof. Carlos",
    time: "18:00 - 19:30",
    daysOfWeek: ["Seg", "Qua", "Sex"],
    gradient: "from-gray-700 to-gray-900",
    spotsLeft: 3,
    totalSpots: 25,
    level: "Avançado",
  },
  {
    id: "4",
    title: "Spinning Intenso",
    instructor: "Profa. Julia",
    time: "19:00 - 20:00",
    daysOfWeek: ["Ter", "Qui", "Sáb"],
    gradient: "from-blue-500 to-cyan-500",
    spotsLeft: 10,
    totalSpots: 30,
    level: "Intermediário",
  },
  {
    id: "5",
    title: "Pilates",
    instructor: "Profa. Marina",
    time: "08:00 - 09:00",
    daysOfWeek: ["Seg", "Qua", "Sex"],
    gradient: "from-pink-400 to-rose-500",
    spotsLeft: 2,
    totalSpots: 12,
    level: "Iniciante",
  },
]

export const mockCategories: Category[] = [
  { id: "1", name: "Corrida", icon: "Footprints" },
  { id: "2", name: "Musculação", icon: "Dumbbell" },
  { id: "3", name: "Yoga", icon: "Heart" },
  { id: "4", name: "Natação", icon: "Waves" },
  { id: "5", name: "CrossFit", icon: "Flame" },
  { id: "6", name: "Luta", icon: "Swords" },
  { id: "7", name: "Dança", icon: "Music" },
  { id: "8", name: "Ciclismo", icon: "Bike" },
]
